[package]
name = "schema-pathfinder"
version = "0.1.0"
edition = "2021"

[features]
default = []
api = ["tiny_http"]

[dependencies]
lexopt = "0.3.2"
postgres = { version = "0.19.13", default-features = false }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
sqlparser = "0.53.0"
tiny_http = { version = "0.12.0", optional = true }

[[bin]]
name = "schema-pathfinder-api"
path = "src/bin/schema-pathfinder-api.rs"
required-features = ["api"]
